spring.application.name=notificationService

server.port=8083

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# Key deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value deserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell consumer which class to create from JSON
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=org.example.notificationservice.event.EmployeeCreatedEvent

# Trusted package
spring.kafka.consumer.properties.spring.json.trusted.packages=org.example.notificationservice.event

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka